### ISSUE TITLE
Cannot insert UTF-8 chars

### ISSUE THREAD

**Issue by jiriknesl** [korma/Korma#150]
I connect using:

(defdb skoleni-db (mysql {
	:db "skoleni"
	:user "root"
	:password ""
	:host "localhost"
	}))

(exec-raw skoleni-db ["SET NAMES 'utf8'"])

Then I create entity

(defentity lectors 
	(table :lectors) 
	(database skoleni-db))

When I try to insert new value with UTF chars (Č and ý in this case):

(insert lectors (values [
			{:id 3 :name "Petr Černý"}]))

I get error:

Failure to execute query with SQL:
INSERT INTO `lectors` (`name`, `id`) VALUES (?, ?)  ::  [Petr Černý 3]
SQLException:
 Message: Incorrect string value: '\xFD' for column 'name' at row 1
 SQLState: HY000
 Error Code: 1366
LOAD FAILURE for sprint-is.test.modules.skoleni
Incorrect string value: '\xFD' for column 'name' at row 1

**Comment by HeGanjie** [comment]
Add query string to `:db` param can solve this
```clojure
(defdb db (mysql {:db   "dbName?useUnicode=true&characterEncoding=UTF-8"
                  :user "root" :password "pw" :host "localhost"}))
```

**Comment by immoh** [comment]
As of 0.4.1 you can also pass driver properties in the spec map:

```clj
(defdb db (mysql {:db   "dbName" :user "root" :password "pw" :host "localhost"
                  :useUnicode true :characterEncoding "UTF-8"}))
```
