### ISSUE TITLE
count aggregate fails in SQLite3

### ISSUE THREAD

**Issue by nathanielksmith** [korma/Korma#152]
It appears that issue #107 affects SQLite3 as well:

An attempt to run the **count** example from [the docs](http://sqlkorma.com
/docs#select) against a sqlite3 db yields the following:

    ppm.db> (select users (aggregate (count :*) :cnt))
 
    Failure to execute query with SQL:
    SELECT COUNT("users".*) AS "cnt" FROM "users"  ::  []
    SQLException:
     Message: [SQLITE_ERROR] SQL error or missing database (near "*": syntax error)
     SQLState: null
     Error Code: 0
    SQLException [SQLITE_ERROR] SQL error or missing database (near "*": syntax error)  org.sqlite.DB.newSQLException (DB.java:383)

The _select count("table".*)_ syntax does not work in sqlite3.

**Comment by immoh** [comment]
Fixed 0fdd4556d946b2020fef411a07047ae4b420f661

**Comment by paomian** [comment]
I think this issue is not fix yet. https://github.com/korma/Korma/commit/0fdd4556d946b2020fef411a07047ae4b420f661 is not in the laster releaes version.
