### ISSUE TITLE
Conflicts with cljsbuild - clojure 1.3 on the classpath

### ISSUE THREAD

**Issue by mullr** [korma/Korma#161]
Korma doesn't play nicely with cljsbuild; having it in the project dependencies causes cljsbuild to fail with a strange classpath error. 

```
Caused by: java.io.FileNotFoundException: Could not locate clojure/instant__init.class or clojure/instant.clj on classpath:
```

Upon further investigation, it seems this could be caused by having an older version of clojure on the classpath.  Sure enough, Korma (or probably one of its dependencies) is pulling in clojure 1.3:

```
> lein classpath
...:/Users/mullr/.m2/repository/org/clojure/clojure/1.3.0/clojure-1.3.0.jar:...
```

A workaround is to exclude clojure in the dependencies line:

```
[korma "0.3.0-beta5" :exclusions [org.clojure/clojure]]
```

**Comment by venantius** [comment]
Korma now runs with Clojure 1.8.0 support by default, so this issue can be closed.
