### ISSUE TITLE
Can't defdb or defentity with postgres schemata other than "public"

### ISSUE THREAD

**Issue by tjb1982** [korma/Korma#163]
With postgresql, we have an architecture like this:

cluster.database.schema.table.field

When you do a `select * from a_table`, what this really means is more like `select * from a_database.a_schema.a_table`.

When you leave out the schema, postgres defaults to the `public` schema.

Korma gives you a way to identify the db and the table, but not the schema (to my knowledge so far). I tried these:

```
(defdb mydb (postgres {:db "mydb" 
                       :user "postgres"
                       :password "postgres"}))

(defentity my_schema.my_table)
```

doesn't work.

I also tried these:

```
(defdb mydbs (postgres {:db "mydb.my_schema"
                        :user "postgres"
                        :password "postgres"}))

(defentity my_table)
```

doesn't work.

**Comment by venantius** [comment]
@dcj's answer is correct.
