### ISSUE TITLE
Can't insert into table

### ISSUE THREAD

**Issue by Eilie** [korma/Korma#165]
<code>(insert users (values {:password "123"}))</code>

Works perfectly fine. But i don't need anything besides timestamp/id/default values inserted into that table so i've tried following
<code>
(insert users (values {}))
Failure to execute query with SQL:
DO 0  ::  []
JdbcSQLException:
 Message: Syntax error in SQL statement "DO[_] 0"; expected "DELETE, DROP, DECLARE, DEALLOCATE, {"; SQL statement:
DO 0 [42001-171]
 SQLState: 42001
 Error Code: 42001
JdbcSQLException Syntax error in SQL statement "DO[_] 0"; expected "DELETE, DROP, DECLARE, DEALLOCATE, {"; SQL statement:
DO 0 [42001-171]  org.h2.message.DbException.getJdbcSQLException (DbException.java:329)
</code>

But as you can see it fails horribly. So question is:
Is it possible to insert into tabe without specifiyng values?

**Comment by venantius** [comment]
`raw-sql` is your friend here.
