### ISSUE TITLE
as-sql not working with a simple join

### ISSUE THREAD

**Issue by mapleoin** [korma/Korma#174]
``` clojure
(select employees (join departments))
```

works fine and returns the right rows, however trying to see the sql behind it: 

``` clojure
(as-sql (select* employees (join departments)))
```

raises this error:

IllegalArgumentException No matching clause:   korma.sql.engine/->sql (engine.clj:395)

This is a simplified example, but it's really annoying to not be able to see the SQL when the queries are more advanced.

**Comment by venantius** [comment]
This has been adequately explained, per above.
