### ISSUE TITLE
"DO 0" is not valid sql according to postgresql

### ISSUE THREAD

**Issue by JacekLach** [korma/Korma#175]
Korma tries to execute that when told to insert an empty arg list: https://github.com/korma/Korma/blob/master/src/korma/sql/engine.clj#L309.

Instead you could use something like `SELECT 0 WHERE 0 = 1`, which returns 0 rows.

**Comment by venantius** [comment]
Unfortunately that code link is now massively stale as it just points to master rather than a particular commit. I'm going to close this issue as lacking context.

**Comment by JacekLach** [comment]
It's just shifted a couple lines:
https://github.com/korma/Korma/blob/857a3fcc031e07339ec6d810e7f3e2ef9a773804/src/korma/sql/engine.clj#L318
