### ISSUE TITLE
Relationship does not  work

### ISSUE THREAD

**Issue by ghost** [korma/Korma#180]
I have the following model:

``` clojure
(defentity projects
  (entity-fields :id :searchid :projname)
   (has-many userprojects {:fk :projectid}))

(defentity userprojects 
  (entity-fields :id :projectid :userid))
```

But the next query:

``` clojure
(select projects (with userprojects))
```

return only records from "projects" entity. The sql-only function return the next result:

``` sql
"SELECT `projects`.* FROM `projects`"
```

Actually, I need to many-to-many relationship, but when I set its (many-to-many instead of has-many) and looking to model "projects" in REPL,  i'm seeing 

``` clojure
:rel {"userprojects" #<Delay@39b5ae: :pending>}}
```

and query throws error:

``` clojure
ClassCastException clojure.lang.PersistentArrayMap cannot be cast to clojure.lang.Named  clojure.core/name (core.clj:1505)
```

**Comment by venantius** [comment]
That sounds like a legitimate bug of some kind but as this issue is over 4 years old I'm going to assume it's probably hard to replicate now. I'm going to close this but if you are able to replicate it we can re-open.
