### ISSUE TITLE
No Driver -> Unhelpful Error

### ISSUE THREAD

**Issue by knusbaum** [korma/Korma#183]
When attempting to use a postgresql database, an absent postgresql driver yeilds the error: 
`CannotAcquireResourceException A ResourcePool could not acquire a resource from its primary factory or source.`
`com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable`

This happens to be the same error that results from a bad connection string, and other problems. I had given up on Korma and was switching to clojure.java.jdbc, which gave me the actual error regarding my lack of postgresql driver.

I installed that, and Korma's working wonderfully now.

It'd be great to have this fixed.

**Comment by venantius** [comment]
I've run into an issue like this one before but I recall the error being more helpful. In any event, I don't think this is likely to still be an issue.

**Comment by knusbaum** [comment]
hopefully...
