### ISSUE TITLE
Replace C3P0 with HikariCP (or add HikariCP support)

### ISSUE THREAD

**Issue by brettwooldridge** [korma/Korma#224]
Thought I'd post there here, as I was emailed (on behalf of HikariCP) asking about support for HikariCP in Korma.  We're not Clojure programmers, but if there is anything the HikariCP team can do to help, let us know.

**Comment by drusellers** [comment]
is this issue still open given the above PRs?

**Comment by immoh** [comment]
It has always been possible to use any datasource implementation by providing `:datasource` key in the db spec map. Korma uses c3p0 by default, and it hasn't been possible to exclude it from dependencies which was fixed by #309.

**Comment by immoh** [comment]
Starting from 0.4.3 it is possible to exclude c3p0 and use any connection pool library.
