### ISSUE TITLE
Disable console logging

### ISSUE THREAD

**Issue by alolis** [korma/Korma#265]
OK, i know the following isn't exactly a big deal, or it's probably not related with korma directly, but it has been driving me insane. I am inserting on purpose a row which causes a duplicate exception, and even though I have disabled logging via log4j for everything, I get messages like this in the console:

```
Failure to execute query with SQL:
INSERT INTO `test` (`test`) VALUES (?)  ::  [1]
MySQLIntegrityConstraintViolationException:
 Message: Duplicate entry '1' for key 'test'
 SQLState: 23000
 Error Code: 1062
```

I also tried to use `logger: NullLogger` in the `defdb` configuration but it didn't help either. If anyone has an idea about this, please, do share with me.

I am using korma with `[mysql/mysql-connector-java "5.1.34"]` by the way.

**Comment by PeterFaiman** [comment]
This is driving me wacko, please kill these lines or make a way to disable them.

>I have no idea what is the purpose of handling exceptions in such way. I have to dig into the history to see if those printlns could be removed entirely.

@immoh I did it for you.

* [better exception handling, copying prints](https://github.com/korma/Korma/commit/f20ce3fb#diff-97785eac1b3a8fccfac3a2a500913e3fR152)
* [exception handling broken out into function, copying prints](https://github.com/korma/Korma/commit/98b46e59#diff-97785eac1b3a8fccfac3a2a500913e3fR111)
* [introduction of the prints, previously exceptions were ignored](https://github.com/korma/Korma/commit/72735ba0#diff-97785eac1b3a8fccfac3a2a500913e3fR114)

I think they were just debugging prints that survived for a long time. Or at least meant to be changed later. They can be safely removed, or at least given a config option.

**Comment by danielflower** [comment]
Nice to see this already fixed, but when can it be released?

**Comment by immoh** [comment]
I'll try to make a release soon, probably next week.

**Comment by elrob** [comment]
We have also noticed this problem and would benefit from the new release.

**Comment by danielflower** [comment]
Just upgraded and it's working great. Thanks!
