### ISSUE TITLE
Pooled connection with Java 1.8 (mac os x yosemite)

### ISSUE THREAD

**Issue by st** [korma/Korma#271]
I am not sure this is a korma issue (rather a C3p0 one) but in case anyone tries to use pooled connection
on Java 1.8 (mac os X) this info may be useful.
Please see this gist for a minimal setup on how to reproduce the problem:
https://gist.github.com/st/c68ca56f796d04dee152

**Comment by immoh** [comment]
https://bugs.openjdk.java.net/browse/JDK-8065397

**Comment by st** [comment]
Upgrading to 8u40 Build b20 (https://jdk8.java.net/download.html) fixes the issue. 
Thank you.
