### ISSUE TITLE
Calling a postgres procedure

### ISSUE THREAD

**Issue by Andati** [korma/Korma#272]
How do I call a postgres proc?

I am currently using row sql. And it fails when I add :results saying there are no results. When I remove the :results, it says results were returned.

**Comment by immoh** [comment]
Could you post a minimal failing case (stored proc) + exec-raw call? Thanks.

**Comment by Andati** [comment]
I found the issue was: I was executing two separate sql statements in one exec-raw call. I was first setting date-style and then calling the proc. I removed the date-style call and it worked ok.
