### ISSUE TITLE
returning previous date on selecting postgres date type

### ISSUE THREAD

**Issue by piyushmandovra** [korma/Korma#275]
i run a simple korma select query in postgres database and for date type in postgres it's returing one day before that exist in our database 
example:
(require '[korma.core :as kc])
(kc/select :users)
;;result
[{:uname "Piyush" :dob  #inst "2015-01-12T18:30:00.000-00:00"}]
while accessing data from pgadmin it's showing dob as 13-01-2015.

**Comment by immoh** [comment]
There's no date handling in Korma, this is completely done by the JDBC driver.

The given date is 2015-01-13 00:00 in UTC+5:30 which I assume is the timezone of your JVM.

**Comment by piyushmandovra** [comment]
ya @immoh  you are right it's related to jvm time-zone
