### ISSUE TITLE
Support for hstore?

### ISSUE THREAD

**Issue by abhishiv** [korma/Korma#279]
I wanna write a query against hstore column, but not sure how to describe it using the korma dsl

`SELECT * FROM ways WHERE tags @> '"place"=>"city"'::hstore`

I can use raw-sql, but i'm just curious how would korma handle something like this?

**Comment by immoh** [comment]
Korma tries to support most commonly used database features, unfortunately queries against hstore columns is out of scope. 

I would try to make the scope of `raw` as small as possible, e.g.:

```clojure
(select :ways (where (raw "tags @> '\"place\"=>\"city\"'::hstore")))
```

and create some helper functions for generating the hstore string from Clojure data structure.
