### ISSUE TITLE
multiple belongs-to same entity

### ISSUE THREAD

**Issue by not3** [korma/Korma#281]
```
(defentity users)
(defentity posts
  (belongs-to users :author_id)
  (belongs-to users :created_by)
  (belongs-to users :updated_by))
```

| table | posts |  |  |  |
| --- | --- | --- | --- | --- |
| title | markdown | author_id | created_by | updated_by |

How to deal with multiple relationships with these entities

**Comment by immoh** [comment]
It is not currently supported by Korma. You can work around by defining a separate entity for each relation, and point them all to users table.

**Comment by venantius** [comment]
This issue has been brought up in other issues on this project and is therefore a duplicate. TL;DR - you can follow the advice above or map the relationship explicitly in the query using joins.
