### ISSUE TITLE
many-to-many relationship error

### ISSUE THREAD

**Issue by cdzwm** [korma/Korma#296]
(ns ip.core
  (:use korma.core korma.db)
  (:require [clojure.string :as str])
  (:import (java.util Calendar))
  (:import (java.text SimpleDateFormat))
  (:gen-class))

(defdb db (mysql {:classname "com.mysql.jdbc.Driver"
                  :user "user"
                  :password "password"
                  :db "db"
                  :host "127.0.0.1"
                  :port "3306"
                  :make-pool? false}))

(defn -main
  "主程序"
  [& args])

(defn reload
  "重新加载程序"
  []
  (load-file "src/ip/core.clj"))

(declare dev div ip login mac net_dev_ext_data net_seg port u_ip)

;; 定义实体
(defentity ip (table :t_ip)
           (many-to-many mac :r_ip_mac {:lfk :ip_id :rfk :mac_id})
           (many-to-many dev :r_ip_dev {:lfk :ip_id :rfk :dev_id}))

(defentity mac (table :t_mac)
           (many-to-many ip :r_ip_mac {:lfk :mac_id :rfk :ip_id})
           (many-to-many dev :r_dev_mac {:lfk :mac_id :rfk :dev_id}))

(defentity dev (table :t_dev)
           (belongs-to div {:fk :div_id}))

(defentity login (table :t_login)
           (belongs-to div {:fk :div_id} ))

(defentity net_dev_ext_data (table :t_net_dev_ext_data)
           (belongs-to dev {:fk :id}))

(defentity net_seg (table :t_net_seg))

(defentity port (table :t_port)
          (belongs-to dev {:fk :dev_id} ))

(defentity conn (table :t_conn) )
(defentity div (table :t_div) )

(defentity u_ip (table :t_u_ip) )

(defn last-ip-list 
  "Recently used ip"
  ([] (vec (map #(:ip %) (select ip (fields :ip) (where {:ct [> (raw "date_sub( now(), INTERVAL 1 DAY)")]})))))
  ([d] (vec (map #(:ip %) (select ip (fields :ip) (where {:ct [> d]}))))))

In repl
ip.core=> (select ip (with dev) (fields :dev.id))

MySQLSyntaxErrorException Unknown column 'dev.id' in 'field list'  sun.reflect.NativeConstructorAccessorImpl.newInstance
0 (:-2)
ip.core=> (dry-run (select ip (with dev) (fields :dev.id)))
dry run :: SELECT `dev`.`id` FROM `t_ip` :: []
dry run :: SELECT `t_dev`.* FROM `t_dev` INNER JOIN `r_ip_dev` ON `r_ip_dev`.`dev_id` = `t_dev`.`id` WHERE (`r_ip_dev`.`
ip_id` = ?) :: [1]
({:t_dev [{:div_id 1, :id 1}], :id 1})
ip.core=>

**Comment by ls4f** [comment]
Try `(korma/configset-naming {:keys string/lower-case :fields string/upper-case})`

**Comment by immoh** [comment]
You are trying to select column "dev.id" from table "t_ip" which doesn't exist. Remove `(fields :dev.id)` from the query.
