### ISSUE TITLE
Table name in postgres is Users, and Korma doesn't seem to add quotes around table name.

### ISSUE THREAD

**Issue by base698** [korma/Korma#321]
leiningen.web=> (defentity Users)
#'leiningen.web/Users
leiningen.web=> (select Users (where {:id 61}) (limit 1))
Failure to execute query with SQL:
SELECT Users.* FROM Users WHERE (Users.id = ?) LIMIT 1  ::  [61]
PSQLException:
 Message: ERROR: relation "users" does not exist
  Position: 21
 SQLState: 42P01
 Error Code: 0

PSQLException ERROR: relation "users" does not exist
  Position: 21  org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2157)

**Comment by immoh** [comment]
Can't repro with this information. How do you define your db?

Quotes should be added by default:

```clj
(defdb mydb (postgres {}))
;;=> {:pool #<Delay@71135d3b: :pending>, :options {:naming {:keys #<core$identity clojure.core$identity@770c23aa>, :fields #<core$identity clojure.core$identity@770c23aa>}, :delimiters ["\"" "\""], :alias-delimiter " AS ", :subprotocol "postgresql"}}
(defentity Users)
;;=> #'user/Users
(sql-only (select Users (where {:id 61}) (limit 1)))
;;=> "SELECT \"Users\".* FROM \"Users\" WHERE (\"Users\".\"id\" = ?) LIMIT 1"
```

**Comment by base698** [comment]
Mine says :delimiters [nil nil] for the line where yours says :delimiters
["\"" "\""]

How do you define the delimiters?  Using defdb I have :delimiters ""

I tried :delimiters ["\"" "\""] as well.

**Comment by base698** [comment]
Never mind, if you don't specify it works fine :)

**Comment by immoh** [comment]
Great :smile:
