### ISSUE TITLE
Should fns be excluded in a project?

### ISSUE THREAD

**Issue by GHExplorer** [korma/Korma#335]
Hi,

I'm getting a NoClassDefFoundError, pointing to korma.sql.fns__init and korma/sql/fns$loading__5340__auto____3182.

Should I be excluding some of the korma functions?

**Comment by immoh** [comment]
Is this still valid? You shouldn't exclude anything. I cannot reproduce this without more information.

**Comment by GHExplorer** [comment]
Don't know, immoh.  I haven't played with it, for a while.
