### ISSUE TITLE
The doc string of korma.core/insert is not proper.

### ISSUE THREAD

**Issue by xzj** [korma/Korma#336]
It says " ...  while MySQL and MSSQL both return a {:generated_key < ID >} hash)". But in fact, while MySQL do return a {:generated_key < ID >} hash, MSSQL returns {:generated_keys < ID >} when I test insert with Microsoft sqlserver jdbc driver version 4.2.

**Comment by immoh** [comment]
Pull request to fix docstring welcome.

**Comment by venantius** [comment]
This seems to have been addressed by #375, so I'm going to close this.
