### ISSUE TITLE
Is there any way to prepend some arbitrary text to the beginning of a SQL query?

### ISSUE THREAD

**Issue by camsaul** [korma/Korma#355]
e.g. If I wanted to add an automatically generated SQL comment to a query executed by korma.

**Comment by venantius** [comment]
I'm going through old issues and trying to clean them up. Has this issue persisted?

If there hasn't been a response to this issue in 2 weeks, I'll close the ticket.

**Comment by camsaul** [comment]
Feel free to close this issue
