### ISSUE TITLE
Korma is dependent on deprecated clojure.java.jdbc functionality

### ISSUE THREAD

**Issue by venantius** [korma/Korma#357]
Korma is now three major versions behind the latest `clojure.java.jdbc` version. This puts it at a place where it now relies on deprecated functionality - running the tests with the `clojure.java.jdbc` version pinned to even `0.5.8` generates tons of warnings around the usage of `query`, `db-transaction*`, `db-do-prepared`, and `db-do-prepared-return-keys`

There's been one PR to try to get things partway updated (#347), but I wanted to see if the maintainers would be open to a PR to get things even more updated than that (i.e. to `0.5.8` or even newer versions)

**Comment by sthomp** [comment]
👍

**Comment by immoh** [comment]
I merged #358 instead.

**Comment by venantius** [comment]
Awesome, thanks!
