### ISSUE TITLE
I get exception: Can't dynamically bind non-dynamic var: clojure.java.jdbc/*as-key*

### ISSUE THREAD

**Issue by jiriknesl** [korma/Korma#360]
I use [korma "0.4.2"] and after adding [org.clojure/java.jdbc "0.6.1"] to my project.clj I get this exception on first attempt to use database.

Until this everything was working just fine.

```
java.lang.IllegalStateException
Can't dynamically bind non-dynamic var: clojure.java.jdbc/*as-key*
Var.java:320	clojure.lang.Var.pushThreadBindings
core.clj:1837	clojure.core/push-thread-bindings
core.clj:1821	clojure.core/push-thread-bindings
db.clj:235	korma.db/do-query
db.clj:233	korma.db/do-query
core.clj:491	korma.core/exec-raw
core.clj:479	korma.core/exec-raw
RestFn.java:423	clojure.lang.RestFn.invoke
user.clj:121	spc.users.models.user/get-user
```

I tried upgrading from older version, upgrading jdbc in project.clj.

I need jdbc in my project because of PGObject solution described here: http://hiim.tv/clojure/2014/05/15/clojure-postgres-json/

**Comment by immoh** [comment]
Korma is not compatible with clojure.java/jdbc 0.6.1. You need to use older version of clojure.java/jdbc. Support for 0.6.1 will be in the next release (see #358).
