### ISSUE TITLE
http://sqlkorma.com/docs is down

### ISSUE THREAD

**Issue by dardenfall** [korma/Korma#389]
I found that writeup a bit more readable than the docs in the repo.  If the site isn't going to be maintained could the source be checked in so it could be hosted locally?  

Thanks for your consideration and the great library.

**Comment by Freid001** [comment]
Viewing the latest archived version on web.archive helped me out, see: https://web.archive.org/web/20171115075822/http://sqlkorma.com/docs

**Comment by dardenfall** [comment]
A mench from my work showed me this:

git clone git@github.com:korma/sqlkorma.git
cd sqlkorma
lein run

Have your own version!

HTH

**Comment by venantius** [comment]
It's now up again.
