### ISSUE TITLE
Connection parameters as URLs is broken

### ISSUE THREAD

**Issue by technomancy** [korma/Korma#62]
The clojure.java.jdbc library [accepts connection parameters as URLs](http://dev.clojure.org/jira/browse/JDBC-21), but Korma assumes it's always a map.

**Comment by ykarikos** [comment]
Up! Support for DATABASE_URL in Korma would be nice since e.g. Heroku Posgresql uses it.

**Comment by immoh** [comment]
Support for :connection-uri is already in master (527565de9eb44a64a5ed88f77f3a97122d0a35db) and will be included in the next release.
