### ISSUE TITLE
Oracle table/column identifiers must be capitalized

### ISSUE THREAD

**Issue by robermann** [korma/Korma#85]
This fails:
(select anag_uten
     (fields :n_nom :n_cogn :n_email )
     (where { :n_uten "GI00051" }))

=>  SELECT "anag_uten"."n_nom", "anag_uten"."n_cogn", "anag_uten"."n_email" FROM "anag_uten" WHERE  ("anag_uten"."n_uten" = ?)  ::  [GI00051]
       SQLException:
       Message: ORA-00942: table or view does not exist

This works:
(select ANAG_UTEN
     (fields :N_NOM :N_COGN :N_EMAIL )
     (where { :N_UTEN "GI00051" }))

**Comment by venantius** [comment]
As this issue is now over 5 years old, I'm going to close it. We can always re-open it if it's a sticking point.
